# Main configuration file for HaloPlex analysis
settings:
  target_generator_handler: ratatosk.ext.scilife.sample.target_generator
  
ratatosk.lib.utils.cutadapt:
  Cutadapt:
    parent_task:
      - ratatosk.lib.utils.cutadapt.InputFastqFile
